"""Generate checked-string fixtures with host-only wasmtime==36.0.0."""
import hashlib
from importlib.metadata import version
from pathlib import Path
import wasmtime

if version("wasmtime") != "36.0.0":
    raise SystemExit("Use the pinned host-only wasmtime==36.0.0")

data = {
    "ascii": (0, b"No terminator"),
    "unicode": (32, "é€😀".encode()),
    "nul": (64, b"A\0Z"),
    "overlong": (96, bytes.fromhex("e08080")),
    "surrogate": (100, bytes.fromhex("eda080")),
    "too_high": (104, bytes.fromhex("f4908080")),
    "truncated": (112, bytes.fromhex("f09080")),
    "continuation": (116, bytes.fromhex("c241")),
    "invalid_lead": (120, bytes.fromhex("ff")),
    "long": (256, b"L" * 256),
    "end": (65535, b"Z"),
}
sections = ["(module (memory 1 1)"]
for name, (offset, payload) in data.items():
    escaped = "".join(f"\\{b:02x}" for b in payload)
    sections.append(f'(data (i32.const {offset}) "{escaped}")')
    sections.append(f'(func (export "{name}") (result i32 i32) i32.const {offset} i32.const {len(payload)})')
sections.extend([
    '(func (export "wrapped") (result i32 i32) i32.const -1 i32.const 8)',
    '(func (export "peek") (param i32) (result i32) local.get 0 i32.load8_u)',
    '(func (export "grow") (result i32) i32.const 1 memory.grow)',
    ')',
])
fixtures = {
    "strings": "\n".join(sections),
    "no_memory": '(module (func (export "noop")))',
    "growing": '(module (memory 0 1) (func (export "grow") (result i32) i32.const 1 memory.grow) (func (export "peek") (result i32) i32.const 0 i32.load8_u))',
}
lines = ["// Generated by generate_fixtures.py; edit that source, not these bytes.",
         "#pragma once", "#include <array>", "#include <cstddef>", "namespace fixtures {"]
for name, wat in fixtures.items():
    binary = bytes(wasmtime.wat2wasm(wat))
    lines.append(f'inline constexpr char {name}_sha256[] = "{hashlib.sha256(binary).hexdigest()}";')
    lines.append(f"inline constexpr std::array<std::byte, {len(binary)}> {name}{{{{")
    for at in range(0, len(binary), 12):
        lines.append("    " + ", ".join(f"std::byte{{0x{b:02x}}}" for b in binary[at:at + 12]) + ",")
    lines.append("}};")
lines.append("} // namespace fixtures")
Path(__file__).with_name("main").joinpath("fixtures.hpp").write_text("\n".join(lines) + "\n", encoding="utf-8")
