"""Generate bounded service-policy fixtures with host-only wasmtime==36.0.0."""
from importlib.metadata import version
from pathlib import Path
import hashlib
import wasmtime

if version("wasmtime") != "36.0.0":
    raise SystemExit("Use the pinned host-only wasmtime==36.0.0")

root = Path(__file__).resolve().parent
fixtures = {
    "workloads": """(module
      (memory (export "memory") 1 1)
      (func (export "echo") (param i32) (result i32) local.get 0)
      (func (export "mixed") (param i32 i64 f32 f64) (result i32 i64 f32 f64)
        local.get 0 local.get 1 local.get 2 local.get 3)
      (func (export "word") (result i32) i32.const 0 i32.load)
      (func (export "grow") (result i32) i32.const 1 memory.grow)
      (func (export "trap") unreachable)
      (func (export "invalid") (result i32) i32.const 65536 i32.load)
      (func (export "divide") (param i32) (result i32) i32.const 1 local.get 0 i32.div_s)
      (func $rec (export "recursion") call $rec)
      (func (export "spin") (loop $again br $again))
      (func (export "too_many") (param i32 i32 i32 i32 i32 i32 i32 i32 i32))
    )""",
    "start_loop": '(module (func $spin (loop $a br $a)) (start $spin))',
    "post_loop": '(module (func (export "__post_instantiate") (loop $a br $a)))',
    "ctor_loop": '(module (func (export "__wasm_call_ctors") (loop $a br $a)))',
    "initialize_loop": '(module (func (export "_initialize") (loop $a br $a)))',
    "imported": '(module (import "blip" "missing" (func)))',
    "large_memory": '(module (memory 2 2))',
}

lines = ["// Generated by generate_fixtures.py; edit that source, not these bytes.",
         "#pragma once", "#include <array>", "#include <cstddef>", "namespace fixtures {"]
for name, text in fixtures.items():
    data = bytes(wasmtime.wat2wasm(text))
    lines.append(f'inline constexpr char {name}_sha256[] = "{hashlib.sha256(data).hexdigest()}";')
    lines.append(f"inline constexpr std::array<std::byte, {len(data)}> {name}{{{{")
    for offset in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"std::byte{{0x{b:02x}}}" for b in data[offset:offset+12]) + ",")
    lines.append("}};")
lines.append("} // namespace fixtures")
(root / "main" / "fixtures.hpp").write_text("\n".join(lines) + "\n", encoding="utf-8")
