"""Generate native import fixtures with host-only wasmtime==36.0.0."""
import hashlib
from importlib.metadata import version
from pathlib import Path
import wasmtime

if version("wasmtime") != "36.0.0":
    raise SystemExit("Use pinned host-only wasmtime==36.0.0")

imports = '''
(import "test.alpha.v1" "echo" (func $echo (param i32) (result i32)))
(import "test.alpha.v1" "wide" (func $wide (param i64) (result i64)))
(import "test.alpha.v1" "float" (func $float (param f32) (result f32)))
(import "test.alpha.v1" "double" (func $double (param f64) (result f64)))
(import "test.alpha.v1" "text" (func $text (param i32 i32 i32) (result i32)))
(import "test.alpha.v1" "noop" (func $noop))
(import "test.alpha.v1" "fail" (func $fail (result i32)))
(import "test.alpha.v1" "slow" (func $slow (result i32)))
(import "test.beta.v1" "echo" (func $beta (param i32) (result i32)))
(import "test.beta.v1" "mixed" (func $mixed (param i32 i64 f32 f64 i32 i64 f32 f64) (result i64)))
(import "test.beta.v1" "wide8" (func $wide8 (param i64 i64 i64 i64 i64 i64 i64 i64) (result i64)))
'''
valid = ['(module', imports, '(memory 1 1)',
    r'(data (i32.const 0) "\c3\a9\e2\82\ac\f0\9f\98\80")',
    r'(data (i32.const 32) "\e0\80\80")', '(data (i32.const 65535) "Z")']
for name, kind in (("echo", "i32"), ("wide", "i64"), ("float", "f32"), ("double", "f64"), ("beta", "i32")):
    valid.append(f'(func (export "{name}") (param {kind}) (result {kind}) local.get 0 call ${name})')
for name, params in (("mixed", "i32 i64 f32 f64 i32 i64 f32 f64"), ("wide8", "i64 i64 i64 i64 i64 i64 i64 i64")):
    valid.append(f'(func (export "{name}") (param {params}) (result i64) ' +
        ' '.join(f'local.get {i}' for i in range(8)) + f' call ${name})')
valid.extend(['(func (export "text") (param i32 i32 i32) (result i32) local.get 0 local.get 1 local.get 2 call $text)',
    '(func (export "noop") call $noop)', '(func (export "fail") (result i32) call $fail)',
    '(func (export "slow") (result i32) call $slow)',
    '(func (export "loop") (loop $forever i32.const 1 call $echo drop br $forever))',
    '(func (export "peek") (param i32) (result i32) local.get 0 i32.load8_u)', ')'])
fixtures = {"valid": "\n".join(valid)}
for key, module, name, params, results in (
    ("unknown", "env", "echo", "i32", "i32"), ("version", "test.alpha.v2", "echo", "i32", "i32"),
    ("alias", "test.alpha.v1", "_echo", "i32", "i32"),
    ("module_nul", r"test.alpha.v1\00evil", "echo", "i32", "i32"),
    ("field_nul", "test.alpha.v1", r"echo\00evil", "i32", "i32"),
    ("argument_type", "test.alpha.v1", "echo", "i64", "i32"),
    ("result_type", "test.alpha.v1", "echo", "i32", "f32"),
    ("many_results", "test.alpha.v1", "echo", "i32", "i32 i64")):
    fixtures[key] = f'(module (import "{module}" "{name}" (func (param {params}) (result {results}))))'
fixtures["memory_import"] = '(module (import "test.alpha.v1" "echo" (memory 1)))'
fixtures["table_import"] = '(module (import "test.alpha.v1" "echo" (table 1 funcref)))'
fixtures["global_import"] = '(module (import "test.alpha.v1" "echo" (global i32)))'
fixtures["start"] = '(module (import "test.alpha.v1" "noop" (func $noop)) (func $start call $noop) (start $start))'
fixtures["constructors"] = '(module (import "test.alpha.v1" "noop" (func $noop)) (func (export "__wasm_call_ctors") call $noop))'
fixtures["export_nul"] = r'(module (func (export "safe\00evil")))'
for count in (32, 33):
    many = [f'(import "test.alpha.v1" "echo" (func $f{i} (param i32) (result i32)))' for i in range(count)]
    fixtures[f"imports_{count}"] = '(module ' + ' '.join(many) + ' (func (export "echo") (param i32) (result i32) local.get 0 call $f0))'

lines = ["// Generated by generate_fixtures.py; edit that source, not these bytes.", "#pragma once",
         "#include <array>", "#include <cstddef>", "namespace fixtures {"]
for name, wat in fixtures.items():
    binary = bytes(wasmtime.wat2wasm(wat))
    lines += [f'inline constexpr char {name}_sha256[] = "{hashlib.sha256(binary).hexdigest()}";',
              f"inline constexpr std::array<std::byte, {len(binary)}> {name}{{{{"]
    for at in range(0, len(binary), 12):
        lines.append("    " + ", ".join(f"std::byte{{0x{b:02x}}}" for b in binary[at:at+12]) + ",")
    lines.append("}};")
lines.append("} // namespace fixtures")
Path(__file__).with_name("main").mkdir(exist_ok=True)
Path(__file__).with_name("main").joinpath("fixtures.hpp").write_text("\n".join(lines) + "\n", encoding="utf-8")
