"""Generate reviewed benchmark bytecode; host-only dependency: wasmtime==36.0.0."""
from pathlib import Path
import hashlib
from wasmtime import wat2wasm

root = Path(__file__).resolve().parent
data = bytes(wat2wasm((root / "fixtures/workloads.wat").read_text(encoding="utf-8")))
rows = [", ".join(f"0x{x:02x}" for x in data[i:i + 16]) for i in range(0, len(data), 16)]
(root / "main/workloads.hpp").write_text(
    "// Generated by generate_fixtures.py; do not edit.\n#pragma once\n#include <cstdint>\n"
    f'inline constexpr char workload_sha256[] = "{hashlib.sha256(data).hexdigest()}";\n'
    "inline std::uint8_t workload_bytes[] = {\n    " + ",\n    ".join(rows) + "\n};\n",
    encoding="utf-8", newline="\n")
print(f"{len(data)} bytes, sha256={hashlib.sha256(data).hexdigest()}")
