"""Generate guest-memory fixtures using host-only wasmtime==36.0.0."""
from importlib.metadata import version
from pathlib import Path
import hashlib
import wasmtime

if version("wasmtime") != "36.0.0":
    raise SystemExit("Use the pinned host-only wasmtime==36.0.0")

fixtures = {
    "memory_access": """(module
      (memory 1 1)
      (data (i32.const 0) "BLIP")
      (func (export "data") (result i32) i32.const 0 i32.load)
      (func (export "f32_aligned") (result i32)
        i32.const 8 f32.const 1.5 f32.store
        i32.const 8 f32.load i32.reinterpret_f32)
      (func (export "f32_unaligned") (result i32)
        i32.const 9 f32.const -0 f32.store align=1
        i32.const 9 f32.load align=1 i32.reinterpret_f32)
      (func (export "f32_math") (result f32)
        i32.const 13 f32.const 1.5 f32.store align=1
        i32.const 13 f32.load align=1 f32.const 2 f32.mul)
      (func (export "f64_aligned") (result i64)
        i32.const 24 f64.const 1.5 f64.store
        i32.const 24 f64.load i64.reinterpret_f64)
      (func (export "f64_unaligned") (result i64)
        i32.const 1 f64.const -0 f64.store align=1
        i32.const 1 f64.load align=1 i64.reinterpret_f64)
      (func (export "f64_math") (result f64)
        i32.const 33 f64.const 1.5 f64.store align=1
        i32.const 33 f64.load align=1 f64.const 2 f64.mul)
      (func (export "nan_bits") (result i32)
        i32.const 17 f32.const nan:0x401234 f32.store align=1
        i32.const 17 f32.load align=1 i32.reinterpret_f32)
      (func (export "signed_byte") (result i32)
        i32.const 43 i32.const 255 i32.store8
        i32.const 43 i32.load8_s)
      (func (export "odd_half") (result i32)
        i32.const 45 i32.const 11259375 i32.store16 align=1
        i32.const 45 i32.load16_u align=1)
      (func (export "last_byte") (result i32)
        i32.const 65535 i32.const 123 i32.store8
        i32.const 65535 i32.load8_u)
      (func (export "bulk") (result i32)
        i32.const 65 i32.const 171 i32.const 33 memory.fill
        i32.const 129 i32.const 65 i32.const 33 memory.copy
        i32.const 161 i32.load8_u)
      (func (export "overlap") (result i32)
        i32.const 201 i32.const 22136 i32.store16 align=1
        i32.const 202 i32.const 201 i32.const 2 memory.copy
        i32.const 202 i32.load16_u align=1)
      (func (export "cross_boundary")
        i32.const 65535 i32.const 1 i32.store16 align=1)
    )""",
    "memory_growth": """(module
      (memory 0 1)
      (func (export "pages") (result i32) memory.size)
      (func (export "grow") (result i32) i32.const 1 memory.grow)
      (func (export "zero") (result i32) i32.const 65532 i32.load)
      (func (export "dirty")
        i32.const 65532 i32.const 305419896 i32.store)
    )""",
}

root = Path(__file__).resolve().parent
lines = ["// Generated by generate_fixtures.py; edit that source, not these bytes.",
         "#pragma once", "#include <array>", "#include <cstddef>", "namespace worker_fixtures {"]
for name, wat in fixtures.items():
    data = bytes(wasmtime.wat2wasm(wat))
    lines.append(f'inline constexpr char {name}_sha256[] = "{hashlib.sha256(data).hexdigest()}";')
    lines.append(f"inline constexpr std::array<std::byte, {len(data)}> {name}{{{{")
    for offset in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"std::byte{{0x{byte:02x}}}" for byte in data[offset:offset+12]) + ",")
    lines.append("}};")
lines.append("} // namespace worker_fixtures")
(root / "main").mkdir(exist_ok=True)
(root / "main/fixtures.hpp").write_text("\n".join(lines) + "\n", encoding="utf-8")
