"""Generate the script store's real-engine fixtures with wasmtime==36.0.0."""
from importlib.metadata import version
from pathlib import Path
import hashlib
import struct
import wasmtime

if version("wasmtime") != "36.0.0":
    raise SystemExit("Use the pinned host-only wasmtime==36.0.0")


def u32(value):
    output = bytearray()
    while True:
        output.append((value & 127) | (128 if value > 127 else 0))
        value >>= 7
        if not value:
            return bytes(output)


def text(value):
    data = value.encode("utf-8")
    return u32(len(data)) + data


def declaration():
    ids = ("armed", "level", "rate", "note")
    defaults = (b"\1", struct.pack("<q", 5), struct.pack("<d", .5), text("hello"))
    data = bytearray(b"BCM1" + u32(6))
    for index, identifier in enumerate(ids):
        data += b"\0" + text(identifier) + text(identifier) + bytes([index, (0, 2, 1, 2)[index]]) + text("") + defaults[index]
        data += bytes([int(index in (1, 2))])
        if index in (1, 2):
            data += struct.pack("<ddd", 0, 100 if index == 1 else 10, 1)
    for kind, identifier in ((1, "fire"), (2, "changed")):
        data += bytes([kind]) + text(identifier) + text("Label")
        if kind == 1:
            data += text("on_fire")
        data += u32(4)
        for index, field in enumerate(ids):
            data += text(field) + bytes([index])
    body = text("blip.controls.v1") + data
    return b"\0" + u32(len(body)) + body


template = """(module
  (memory (export "memory") 1 1)
  (global (export "blip_controls_buffer_v1") {arena})
  (global (export "mutable") (mut i32) (i32.const 7))
  (global (export "wide") i64 (i64.const -1))
  (global (export "negative") i32 (i32.const -1))
  (func (export "on_fire") (param i32 i64 f64 i32 i32)
    i32.const 0 local.get 0 i32.store
    i32.const 8 local.get 1 i64.store
    i32.const 16 local.get 2 f64.store
    i32.const 24 local.get 3 i32.store
    i32.const 28 local.get 4 i32.store)
)"""
definitions = {"valid": "i32 (i32.const 1024)", "mutable_buffer": "(mut i32) (i32.const 1024)",
               "wide_buffer": "i64 (i64.const 1024)", "outside_buffer": "i32 (i32.const 65535)"}
lines = ["// Generated by generate_fixtures.py; edit that source.", "#pragma once", "#include <array>", "#include <cstddef>",
         "namespace fixtures {"]
engine = wasmtime.Engine()
for name, arena in definitions.items():
    module = bytes(wasmtime.wat2wasm(template.replace("{arena}", arena))) + declaration()
    wasmtime.Module.validate(engine, module)
    lines += [f'inline constexpr char {name}_sha256[] = "{hashlib.sha256(module).hexdigest()}";',
              f"inline constexpr std::array<std::byte, {len(module)}> {name}{{{{"]
    for offset in range(0, len(module), 12):
        lines.append("    " + ", ".join(f"std::byte{{0x{b:02x}}}" for b in module[offset:offset+12]) + ",")
    lines.append("}};")
lines.append("} // namespace fixtures")
(Path(__file__).resolve().parent / "main/fixtures.hpp").write_text("\n".join(lines) + "\n", encoding="utf-8")
